### ISSUE TITLE
Feature request: invite restriction

### ISSUE THREAD

**Issue by toushin-taishi** [8go/matrix-eno-bot#20]
Hello @8go,

Is it possible to specify the account or room that the BOT will accept invites from?
I hope you would consider this request in the future release of matrix-eno-bot.

Thank you for your hard work!

**Comment by troglodyne** [comment]
Another thing that could potentially be of use here is restricting certain commands from execution based on the account or room. That said, currently one can implement command blacklisting/whitelisting for *users* on a per-command basis now with the ENO_SENDER environment variable. That said, I could still see value in doing it on a bot level, not command level, especially since then you can restrict certain commands by room as well.

My thoughts RE implementation:
* config.yaml likely should hold a group of "user groups" which one can then use to specify specific behavior for.
example (acls standing for "Access Control Lists) with user-defined lists:
```
acls:
  admin-users:
    - @8go:matrix.org
  trusted-users:
    - @toushin-taishi:matrix.org
    - @teodesian:some.other.server
  allowed-rooms:
    - #matrix:matrix.org
    - #kool-kidz-only:my.homeserver.name
```
* Additionally in config.yaml, one could then specify ACLs related to bot invitation:
```
invitation-permissions:
  users:
    - admin-users
    - trusted-users
  rooms:
    - allowed-rooms
```
* over in commands.yaml, we could additionally specify (optional) ACLs to restrict a command by:
```
hold_my_beer:
  regex: "^yolo$"
  cmd: do_something_very_dangerous.sh
  help: "I'ts cool, I totally know what I'm doing"
  markdown_convert: true
  formatted: true
  code: false
  users: admin-users
  rooms: allowed-rooms
```

As to the actual code implementation, it seems pretty straightforward, as ultimately it's a matter of just updating the command/config dictionary logic along with getting bot_commands.py to do the right stuff for commands (reply "I'm sorry, I can't let you do that, Dave" when command ACL requirements not met) and callbacks.py to do the right stuff as it regards invites (ignore invites if they are not matching entries in the ACLs).
